[package]
name = "pas2rust"
version = "0.1.0"
edition = "2021"
description = ""
authors = [""]
homepage = ""
repository = ""
license = "MIT"
exclude = [
    "migrations/*",
    "tests/*",
    "tests",
    "schema.rs",
    "diesel.toml",
    "main.rs"
]
keywords = [""]
[package.metadata.scripts]
dev = "cargo fmt && cargo clippy && cargo run"
test = "cargo fmt && cargo clippy && cargo test --all-features"
deploy = "cargo fmt && cargo clippy && cargo package && cargo publish"
clean = "cargo clean && rm -rf target && rm -rf dist && rm tailwind.css && rm -rf node_modules"
gui = "cargo fmt && cargo clippy && tailwindcss -i ./styles/main.css -o ./tailwind.css && trunk serve --open"

[package.metadata.docs.rs]
logo-url = "https://i.imgur.com/svdzGva.jpg"

[dependencies]
actix-web = {version = "4.9.0", optional = true}
async-trait = "0.1.83"
bincode = {version = "1.3.3", optional = true }
chrono = { version = "0.4.38", features = ["serde"], optional = true }
colorful = { version = "^0.3.2", optional = true }
diesel = { version = "2.2.5", features = ["postgres", "r2d2"], optional = true }  
hex = { version = "0.4.3", optional = true }
proc-macro2 = "^1.0.89"
quote = "^1.0.37"
r2d2 = {version = "0.8.10", optional = true}
rand = "0.8.5"
rand_regex = "0.17.0"
redis = { version =  "0.27.5", features = ["r2d2"], optional = true }
regex = "1.11.1"
serde = { version = "1.0.214", features = ["derive"], optional = true }
serde_json = { version = "1.0.132", optional = true }
syn = { version = "2.0.87", features = ["full", "visit-mut"] }
tokio = {version = "1.41.1", features = ["full"]}
toml = {version = "0.8.19", optional = true }
uuid = {version = "1.11.0", features=["v4"]}

[lib]
name = "pas2rust"
proc-macro = true
path = "src/lib.rs"

[features]
default = ["full"]
repository = ["r2d2", "redis", "diesel"]
actix = ["actix-web"]
math = []
virus = []
getters = []
logging = ["chrono", "colorful"]
setters = []
builder = []
hexadecimal = ["hex"]
bytes = []
json = ["serde", "serde_json"]
to = []
service = []
observer = []
full = ["virus", "repository", "to", "builder", "bytes","actix", "math", "getters", "json", "logging", "setters", "bincode", "hexadecimal", "observer"]
diesel = ["dep:diesel"]
